name: video
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - torchaudio
  - opencv
  - libjpeg-turbo # Explicitly ask for libjpeg
  - pip
  - pip:
    - easyocr
    - pillow